baseURL = "/"
languageCode = "de-DE"
title = "JGV Diepholz"
themesDir = "themes"
theme = "hugo-hero-theme-master"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Der JGV Diepholz ...."
    meta_og_title = "JGV Diepholz"
    meta_og_type = "website"
    meta_og_url = "https://jgv-diepholz.de"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Der JGV Diepholz.."
    meta_twitter_card = "JGV Diepholz"


[[menu.main]]
	name = "Der Verein"
    url = "/verein/"
    weight = 1

[[menu.main]]
    name = "Ausbildung"
	url = "/ausbildung/"
    weight = 2

[[menu.main]]
    name = "Termine"
    url = "/termine/"
    weight = 3

[[menu.main]]
    name = "Prüfungen"
    url = "/pruefungen/"
    weight = 4

[[menu.main]]
    name = "Service"
    url = "/services/"
    weight = 5

[[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 6

[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 7

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"